load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "config",
    srcs = ["config.py"],
)

py_library(
    name = "agents_lib",
    srcs = [
        "a2ui_transpiler.py",
        "agents/task_agent/__init__.py",
        "agents/task_agent/task_agent.py",
    ],
    data = ["agents/task_agent/agent.json"],
    deps = [":config"],
)

py_binary(
    name = "agent",
    srcs = ["main.py"],
    imports = ["."],  # Support local directory imports
    main = "main.py",
    deps = [
        ":agents_lib",
        ":config",
    ],
)

py_test(
    name = "test_config",
    size = "small",
    srcs = ["tests/test_config.py"],
    imports = ["."],  # Support local directory imports
    deps = [
        ":config",
    ],
)

py_test(
    name = "test_agent",
    size = "small",
    srcs = ["tests/test_agent.py"],
    imports = ["."],  # Support local directory imports
    deps = [
        ":agents_lib",
    ],
)

py_test(
    name = "test_a2ui_transpiler",
    size = "small",
    srcs = ["tests/test_a2ui_transpiler.py"],
    imports = ["."],  # Support local directory imports
    deps = [
        ":agents_lib",
    ],
)

sh_binary(
    name = "dev",
    srcs = ["run_agent.sh"],
    data = [
        ".env.dev.toml",
        ".env.local.toml",
        ".env.toml",
        "config.py",
        "main.py",
        ":agents_lib",
    ],
    tags = [
        "local",
        "no-sandbox",
    ],
)
