# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM gcr.io/distroless/static-debian12:latest

# Set working directory
WORKDIR /

# Copy the statically compiled Linux binary from build context
COPY server_bin /server

# Copy environment configuration files
COPY .env.toml /
COPY .env.dev.toml /

# Expose API port
ENV MODENV_RUNTIME=dev
EXPOSE 8080

# Execute server
ENTRYPOINT ["/server"]
